### ISSUE TITLE
demo_analyzer can not be run

### ISSUE THREAD

**Issue by simonecid** [cms-l1t-offline/cms-l1t-analysis#24]
I am trying to run the demo_analyzer, but I can not. 
I setup my environment by doing:
```bash
git clone git@github.com:cms-l1t-offline/cms-l1t-analysis.git
source bin/env.sh
make setup
```
when I try to run:
```bash
python bin/analyze -a demo_analyzer -i 'data/L1Ntuple_*.root' -n 1000
```
I get:
```bash
The runtime for info took 2.50339508057e-05 seconds to complete
================================================================================
Starting CMS L1T Analsysis
================================================================================
Will write output to:  workspace/20170420-rev_1
Traceback (most recent call last):
  File "bin/analyze", line 147, in <module>
    isok = run(args)
  File "bin/analyze", line 116, in run
    process_tuples(args, analyzer)
TypeError: 'NoneType' object is not callable

```

**Comment by benkrikler** [comment]
Hi Simone, can you try to update your copy of the code and run again?  This issue should be fixed now.

**Comment by simonecid** [comment]
Hi Ben, it is working now, many thanks.

**Comment by benkrikler** [comment]
Excellent. I'm closing this issue then.
