### ISSUE TITLE
cmsl1t can only be executed in cms-l1t-analysis project directory

### ISSUE THREAD

**Issue by benkrikler** [cms-l1t-offline/cms-l1t-analysis#41]
Because of the relative paths in this point of the code:
https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/cmsl1t/playground/eventreader.py#L13
we can only run from the top-level directory of this project.

There are two ways I can see this being solved:
1. Add the top-level directory to LD_LIBRARY_PATH or the similar ROOT variable in `bin/env.sh`
2. Have `make setup` generate a set of import variables that can be used within our python code to get the path of the top-level directory etc and retrieve and use this to build the absolute path in the eventreader code, above.
3. Have `bin/env.sh` create a new environment variable for the top-level directory of the project and retrieve and use this to build the absolute path in the eventreader code, above.

Any thoughts @kreczko?

**Comment by kreczko** [comment]
For this it would be useful to have an error message. I tried to run outside of the project:
```bash
vagrant up
vagrant ssh
cd /vagrant
source bin/env.sh
cd
# modified data location in demo config
cmsl1t -c /vagrant/config/demo.yaml
```
gives
```
================================================================================
Starting CMS L1T Analsysis
================================================================================
Try loading analyzer:cmsl1t.analyzers.demo_analyzer
Successfully loaded analyzer:cmsl1t.analyzers.demo_analyzer
================================================================================
Loading data
================================================================================
Input files:
['/vagrant/data/L1Ntuple_test_1.root', '/vagrant/data/L1Ntuple_test_2.root', '/vagrant/data/L1Ntuple_test_3.root']
ERROR:ROOT.TUnixSystem.FindDynamicLibrary] build/L1TAnalysisDataformats.so does not exist in /home/vagrant/.cache/rootpy/x86_64-60800/dicts:/home/vagrant/.cache/rootpy/x86_64-60800/modules:/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib64:/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib:/cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2/x86_64-slc6/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/lib:/cvmfs/grid.cern.ch/emi3ui-latest/usr/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/usr/lib:.:/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.08.00-9d886/x86_64-slc6-gcc62-opt/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Traceback (most recent call last):
  File "/vagrant/bin/cmsl1t", line 130, in <module>
    analyze()
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click_log/core.py", line 94, in wrapper
    return f(*args, **kwargs)
  File "/vagrant/bin/cmsl1t", line 114, in analyze
    isok = run(config, nevents, reload_histograms)
  File "/vagrant/bin/cmsl1t", line 69, in run
    process_tuples(config, nevents, analyzers)
  File "/vagrant/cmsl1t/utils/timers.py", line 13, in wrapper
    value = func(*args, **kwargs)
  File "/vagrant/bin/cmsl1t", line 38, in process_tuples
    from cmsl1t.playground.eventreader import EventReader
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 303, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/vagrant/cmsl1t/playground/eventreader.py", line 16, in <module>
    ROOT.gSystem.Load('build/L1TAnalysisDataformats.so')
  File "/vagrant/cmsl1t/playground/eventreader.py", line 16, in <module>
    ROOT.gSystem.Load('build/L1TAnalysisDataformats.so')
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/rootpy-0.8.1-py2.7.egg/rootpy/logger/magic.py", line 247, in intercept_next_line
    raise exception
rootpy.ROOTError: level=3000, loc='TUnixSystem::FindDynamicLibrary', msg='build/L1TAnalysisDataformats.so does not exist in /home/vagrant/.cache/rootpy/x86_64-60800/dicts:/home/vagrant/.cache/rootpy/x86_64-60800/modules:/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib64:/cvmfs/sft.cern.ch/lcg/views/LCG_latest/x86_64-slc6-gcc62-opt/lib:/cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2/x86_64-slc6/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/lib:/cvmfs/grid.cern.ch/emi3ui-latest/usr/lib64:/cvmfs/grid.cern.ch/emi3ui-latest/usr/lib:.:/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.08.00-9d886/x86_64-slc6-gcc62-opt/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64'
```

After fixing `ROOT.gSystem.Load('build/L1TAnalysisDataformats.so')` the next issue is the include path:
```
In file included from L1TAnalysisDataformats_ACLiC_dict dictionary payload:10:
/vagrant/external/L1Trigger/L1TNtuples/interface/L1AnalysisAllDataformats.h:1:10: fatal error: 'L1Trigger/L1TNtuples/interface/L1AnalysisBMTFInputsDataFormat.h' file not found
#include "L1Trigger/L1TNtuples/interface/L1AnalysisBMTFInputsDataFormat.h"
```

Once I added the paths to the ROOT include path, all was fine. PR coming in a sec.
